
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alumno
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOpcion = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpcion.setBackground(new java.awt.Color(255, 204, 204));
        lblOpcion.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        getContentPane().add(lblOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 140, 100));

        jcbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Grapes", "Kiwi", "Cherry" }));
        jcbOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(jcbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jcbOpciones.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/canasta.png"))); // NOI18N
        jLabel1.setText("Fruits!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 200, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        // TODO add your handling code here:
       int op= jcbOpciones.getSelectedIndex();
         
       switch (op) {
          
           case 0: JOptionPane.showMessageDialog(null,
                   "Numero 1",
                   "Opcion Seleccionada",
                   JOptionPane.INFORMATION_MESSAGE);
                   lblOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/apple.png")));
             
                
                break;
                
           case 1: JOptionPane.showMessageDialog(null,
                   "Numero 2",
                   "Opcion Seleccionada",
                   JOptionPane.INFORMATION_MESSAGE);
                 lblOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/grapes.png")));
                
                break;
                
           case 2: JOptionPane.showMessageDialog(null,
                   "Numero 3",
                   "Opcion Seleccionada",
                   JOptionPane.INFORMATION_MESSAGE);
                 lblOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/kiwi.png")));
                
                break;
                
           case 3: JOptionPane.showMessageDialog(null,
                   "Numero 4",
                   "Opcion Seleccionada",
                   JOptionPane.INFORMATION_MESSAGE);
                 lblOpcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cherry.png")));
                
                break;
               
       }
        
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JLabel lblOpcion;
    // End of variables declaration//GEN-END:variables
}
