
import java.net.URL;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alumno
 */
public class Acceso extends javax.swing.JFrame {

    String ruta = "";
    URL url = null;
    ImageIcon icon = null;
    
    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblOpcion = new javax.swing.JLabel();
        jcbOpciones = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlista = new javax.swing.JList<>();
        btnLista = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setForeground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblOpcion.setBackground(new java.awt.Color(255, 204, 204));
        lblOpcion.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        getContentPane().add(lblOpcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 220, 100));

        jcbOpciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Apple", "Grapes", "Kiwi", "Cherry" }));
        jcbOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jcbOpciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbOpcionesActionPerformed(evt);
            }
        });
        getContentPane().add(jcbOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));
        jcbOpciones.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/canasta.png"))); // NOI18N
        jLabel1.setText("Fruits!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, 50));

        jlista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Opcion 1", "Opcion 2", "Opcion 3", "Opcion 4", "Opcion 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlista);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 150, 150));

        btnLista.setText("Opcion");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcbOpcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbOpcionesActionPerformed
        // TODO add your handling code here:
       int op= jcbOpciones.getSelectedIndex();
       String cadena = jcbOpciones.getSelectedItem().toString();
         
       switch (op) {
          
           case 0: mostrarImagen("/img/apple.png", op+1, cadena);
             
                break;
                
           case 1: mostrarImagen("/img/grapes.png", op+1, cadena);
                
                break;
                
           case 2: mostrarImagen("/img/kiwi.png", op+1, cadena);
                
                break;
                
           case 3: mostrarImagen("/img/cherry.png", op+1, cadena);
                
                break;
                
           default:
               throw new AssertionError();
               
       }
        
    }//GEN-LAST:event_jcbOpcionesActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        int opc= jlista.getSelectedIndex();
        
        switch (opc) {
            case -1: JOptionPane.showMessageDialog(null,
                                                   "No ha seleccionado Nada",
                                                   "Mensaje",
                                                   JOptionPane.WARNING_MESSAGE);
            
            break;
            
            case 0:
            case 1:
            case 2:
            case 3:
            case 4: mostrarCuadro(opc+1);
            
            break;
        
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        
        eliminar();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarActionPerformed

    public void mostrarCuadro(int op){
        JOptionPane.showMessageDialog(null,
                        "Opción No:"+ op,
                        "Opción Seleccionada",
                        JOptionPane.INFORMATION_MESSAGE);
    }
    
    public void limpiar(){
        
    }
    public void eliminar(){
        int pos = jlista.getSelectedIndex();
        jlista.remove(this);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }
    
    public void mostrarImagen(String urlImagen, 
                                     int opcion,
                                     String cad){
        url = this.getClass().getResource(urlImagen);
        icon = new ImageIcon(url);
        lblOpcion.setIcon(icon);
        lblOpcion.setText("Opcion: " + opcion + " Texto: " + cad);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbOpciones;
    private javax.swing.JList<String> jlista;
    private javax.swing.JLabel lblOpcion;
    // End of variables declaration//GEN-END:variables
}
